### ISSUE TITLE
TinyImageNet Training/Testing Script ?

### ISSUE THREAD

**Issue by SilenceMonk** [Intelligent-Computing-Lab-Yale/Energy-Separation-Training#1]

**Comment by SilenceMonk** [comment]
Thanks for the excellent work! As I'm walking around datasets that resemble ImageNet, it'll be helpful if the reproducible training/testing script is provided!

**Comment by MoitraAbhi** [comment]
Hi sorry for the late reply. Do you want the training code for the layer wise energy separation or the standard training?

**Comment by SilenceMonk** [comment]
Yes if possible!

**Comment by MoitraAbhi** [comment]
Hello @SilenceMonk. I really appreciate your interest in our research. We have added the files for training the detector on the tinyimagnet dataset. use the tiny_train.sh file to run all the files.

**Comment by SilenceMonk** [comment]
thx!

**Comment by SilenceMonk** [comment]
Thx for your kind reply!
